# File: .readthedocs.yaml

version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - sed -i '2i\import sys\\nprint("DEBUG:sys.path={}".format(sys.path))\\nimport cmd\\nprint("DEBUG:cmd.__file__={}".format(cmd.__file__))' /home/docs/.asdf/installs/python/3.11.9/lib/python3.11/pdb.py


# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt
